version: "3.8"

services:
  db:
    image: postgres:16
    container_name: custom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: code_quest
      POSTGRES_USER: code_quest
      POSTGRES_PASSWORD: code_quest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
